In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("Telco_customer_churn.csv")
print("shape fo the data ",df.shape)
print("columns of the data ",df.columns)
print("sata types ",df.dtypes)
print("null values ",df.isnull().sum())
print(df["Churn Label"].value_counts())

shape fo the data  (7043, 33)
columns of the data  Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')
sata types  CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object
null values  CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64
Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [2]:
df["Total Charges"].dtypes

dtype('O')

In [3]:
df["Total Charges"]=pd.to_numeric(df["Total Charges"],errors="coerce")

In [4]:
df["Total Charges"].isnull().sum()

np.int64(11)

In [5]:
df["Total Charges"]=df["Total Charges"].fillna(df["Total Charges"].median())

In [6]:
df["Total Charges"].median()

np.float64(1397.475)

In [7]:
drop_columns=["CustomerID","Country","State","City","Lat Long","Latitude","Longitude","Zip Code","Churn Score","Churn Label","Churn Reason","Count"]

In [8]:
model_df=df.drop(columns=drop_columns)

In [9]:
model_df.head(2)

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value,CLTV
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,3239
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,2701

In [10]:
model_df["Avg_monthSpend"]=model_df["Total Charges"]/model_df["Tenure Months"]+1

In [11]:

model_df["Num Service"] =( model_df["Phone Service"].apply(lambda x: 1 if x == "Yes" else 0)+ 
model_df["Multiple Lines"].apply(lambda x: 1 if x=="Yes" else 0)+
model_df["Online Security"].apply(lambda x : 1 if x=="Yes" else 0)+
model_df["Online Backup"].apply(lambda x: 1 if x=="Yes" else 0)+
model_df["Device Protection"].apply(lambda x: 1 if x=="Yes" else 0)+
model_df["Tech Support"].apply(lambda x :1 if x=="Yes" else 0)+
model_df["Streaming TV"].apply(lambda x:1 if x =="Yes" else 0)+
model_df["Streaming Movies"].apply(lambda x: 1 if x=="Yes" else 0))

In [12]:
print(model_df["Num Service"].value_counts().sort_index())

Num Service
0      80
1    1701
2    1188
3     965
4     922
5     908
6     676
7     395
8     208
Name: count, dtype: int64

In [13]:
model_df["Is Month to Month"]=model_df["Contract"].apply(lambda x: 1 if x =="Month-to-month"else 0 )
model_df["Fiber"]=model_df["Internet Service"].apply(lambda x: 1 if x =="Fiber optic" else 0)

In [14]:
print(model_df["Is Month to Month"].value_counts())
print(model_df["Fiber"].value_counts())

Is Month to Month
1    3875
0    3168
Name: count, dtype: int64
Fiber
0    3947
1    3096
Name: count, dtype: int64

In [15]:
model_df.select_dtypes(include="string").columns

Index([], dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
encoder=LabelEncoder()

In [18]:
for col in model_df.select_dtypes(include="string").columns:
    model_df[col]=encoder.fit_transform(model_df[col])

In [19]:
x=model_df.drop(["Churn Value"],axis =1)
y=model_df["Churn Value"]

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2 ,stratify=y,random_state=42)

In [22]:
print(x_train.shape)
print(x_test.shape)

(5634, 24)
(1409, 24)

In [23]:
print(x_train.isnull().sum()[x_train.isnull().sum() > 0])

Series([], dtype: int64)

In [24]:
import numpy as np
x_train=x_train.replace([np.inf,-np.inf], np.nan)
x_test=x_test.replace([np.inf,-np.inf],np.nan)
for col in x_train.select_dtypes(include='object').columns:
    x_train[col] = encoder.fit_transform(x_train[col].astype(str))
    x_test[col]  = encoder.transform(x_test[col].astype(str))

x_train.fillna(x_train.median())
x_test.fillna(x_test.median())

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,CLTV,Avg_monthSpend,Num Service,Is Month to Month,Fiber
2196,1,0,1,0,72,1,2,1,2,2,...,2,1,1,114.05,8468.20,4842,118.613889,8,0,1
3549,0,1,0,0,8,1,2,1,0,0,...,0,1,1,100.15,908.55,5157,114.568750,5,1,1
3515,0,0,1,0,41,1,2,0,2,2,...,1,1,1,78.35,3211.20,2894,79.321951,6,0,0
5162,1,0,1,0,18,1,0,1,0,0,...,0,0,2,78.20,1468.75,2831,82.597222,3,1,1
4642,0,0,1,0,72,1,2,0,2,2,...,2,1,1,82.65,5919.35,4324,83.213194,7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660,0,0,1,1,49,1,0,0,2,2,...,1,1,3,87.20,4345.00,4567,89.673469,7,0,0
5150,1,0,1,1,28,1,0,2,1,1,...,2,1,1,20.30,487.95,2948,18.426786,1,0,0
4708,1,0,0,0,5,1,0,2,1,1,...,0,0,0,20.65,93.55,5597,19.710000,1,1,0
5381,0,0,0,0,56,1,0,2,1,1,...,2,0,0,19.70,1051.90,4831,19.783929,1,0,0
6000,0,0,1,1,72,1,2,0,2,2,...,2,1,0,70.45,5165.70,4463,72.745833,6,0,0

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf=RandomForestClassifier()

In [27]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [28]:
y_pred=rf.predict(x_test)

In [29]:
y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [30]:
from sklearn.metrics import classification_report

In [31]:
cr=classification_report(y_test,y_pred)

In [39]:
print(cr)

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1035
           1       0.63      0.51      0.56       374

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [33]:
y_prob=rf.predict_proba(x_test)[:,1]

In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1035
           1       0.63      0.51      0.56       374

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [43]:
from sklearn.metrics import roc_auc_score

In [45]:
print("Roc_auc",roc_auc_score(y_test,y_prob))

Roc_auc 0.8367614766591749

In [37]:
import pickle

# Save the model
with open("churn_model.pkl", "wb") as f:
    pickle.dump(rf, f)

# Save the scaler too (needed for preprocessing)
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

print("Model and scaler saved!")
```

This creates two files in the same folder as your notebook:
- `churn_model.pkl` — your trained Random Forest
- `scaler.pkl` — your StandardScaler

Run that and tell me it printed "Model and scaler saved!" 👇

---

### While You Do That — Here's The Plan

Once saved, we'll create one file called `app.py` in the same folder. The structure will be:
```
Your Project Folder/
│
├── churn_model.pkl      ← model you're saving now
├── scaler.pkl           ← scaler you're saving now
├── app.py               ← Streamlit app we'll build next
└── your_notebook.ipynb  ← your existing notebook

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [46]:
import pickle

In [49]:
with open("churn-prediction","wb") as f:
    pickle.dump(rf ,f)
print("model  saved")

model  saved